// <auto-generated />
using System;
using ElectricityApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220902094840_AddElectricityToDatabase")]
    partial class AddElectricityToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElectricityApp.Models.Electricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("OBJ_GV_TIPAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OBJ_NUMERIS")
                        .HasColumnType("int");

                    b.Property<string>("OBT_PAVADINIMAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PL_T")
                        .HasColumnType("datetime2");

                    b.Property<string>("TINKLAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("consumed")
                        .HasColumnType("float")
                        .HasColumnName("P+");

                    b.Property<double>("produced")
                        .HasColumnType("float")
                        .HasColumnName("P-");

                    b.Property<double>("producedAndConsumed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Electricities");
                });
#pragma warning restore 612, 618
        }
    }
}
